name: Atualizar LISTA.xlsx

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-lista-xlsx
  cancel-in-progress: false

jobs:
  update-excel:
    runs-on: ubuntu-latest

    env:
      AZDO_ORGANIZATION: promob-dev
      AZDO
